<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_pemasangan_alat_model');
        $this->load->model('Jual_model');
        $this->load->model('App_bts_model');
        $this->load->model('App_client_model');
        $this->load->model('Mms7_detjual_model');
        $this->load->library('form_validation');     
	    $this->load->library('datatables');
    }

    //total semua harga 
    //total penyusutan dari bulan
    //lebih dari bulan yang ditentukan
    public function index()
    {
        $data = array(
            'action' => base_url('login/login_action'),
        );
        $this->load->view('login',$data);
        
    } 
    public function login_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->session->set_flashdata('message', '
                    <div class="alert alert-danger">
                        <h4><i class="icon fa fa-warning"></i> Gagal</h4>
                        '.validation_errors().'
                    </div>
                  ');
            $this->index();
        }else {
            $username=$this->input->post('username',TRUE);
            $password=md5($this->input->post('password',TRUE));
            $data = array(
                'username'  =>  $username,
                'password'  =>  $username,
            );
            $data= $this->curl->simple_post('http://app.solonet.net.id/login/login_api.php',$data, array(CURLOPT_BUFFERSIZE => 10)); 
            $result=json_decode($data);
            print_r($result);
            if ($result->status=='Sukses') {
                $data = array(
                    'username' => $result->username, 
                    'status' => $result->status, 
                );
                $this->session->set_userdata($data);
                print_r($this->session->userdata());
                $this->session->set_flashdata('message', '
                        <div class="alert alert-success">
                           <h4><i class="icon fa fa-check-circle"></i> Sukses Login</h4>
                           Silahkan melanjutkan.
                        </div>
                    ');
                redirect(base_url('data_pemasangan_alat'));
            }else{
                $this->session->set_flashdata('message', '
                    <div class="alert alert-danger">
                        <h4><i class="icon fa fa-warning"></i> Gagal</h4>
                        username atau Password salah.
                    </div>
                  ');
                $this->index();
            }
        }
    } 

    public function login_api() {
        // if($this->input->post()){
        //     $this->session->set_userdata('id_user', $this->input->post('id_user', TRUE));
        //     $this->session->set_userdata('nama_user', $this->input->post('nama_user', TRUE));
        //     $this->session->set_userdata('username', $this->input->post('username', TRUE));
        //     $this->session->set_userdata('level', $this->input->post('level', TRUE));

        //     redirect(base_url(''));
        // } else {
        //     redirect('../../');
        // }
        echo $this->input->post('level', TRUE);
    }

    public function logout(){
        $this->session->sess_destroy();
        redirect(base_url('login'));
    }
    public function _rules() 
    {
        $this->form_validation->set_message('required', '{field} harus diisi.');
        $this->form_validation->set_message('cek_select','{field} harus dipilih.');

    	$this->form_validation->set_rules('username', 'Username', 'trim|required');
        $this->form_validation->set_rules('password', 'Password', 'trim|required');

        $this->form_validation->set_error_delimiters('<p style="margin-bottom:0;margin-top:0;">', '</p>');
    }

}

/* End of file Data_pemasangan_alat.php */
/* Location: ./application/controllers/Data_pemasangan_alat.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-20 03:56:45 */
/* http://harviacode.com */