<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_pemasangan_alat_model extends CI_Model
{

    public $table = 'data_pemasangan_alat';
    public $id = 'id_pemasangan_alat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    // datatables
    function json() {
        $this->datatables->select('data_pemasangan_alat.id_user,data_pemasangan_alat.nota,id_pemasangan_alat,tanggal_pemasangan,type_user,nama,jumlah_alat,data_pemasangan_alat.harga,umur_alat');
        $this->datatables->from('data_pemasangan_alat');
        //add this line for join
        $this->datatables->join('mms7.detjual', 'penyusutan.data_pemasangan_alat.nota = mms7.detjual.nota');
        $this->datatables->where('id_alat = kode');
        $this->datatables->where('status_pemasangan','aktif');
        // $this->datatables->join('app.mon_databts', 'penyusutan.data_pemasangan_alat.id_user = app.mon_databts.id_bts');
        // $this->datatables->join('app.sale_register', 'penyusutan.data_pemasangan_alat.id_user = app.sale_register.id_register');
            // <a href="'.base_url('data_pemasangan_alat/delete/$1').'" class="btn btn-sm btn-flat btn-default" onclick="javasciprt: return confirm(\'Apakah anda yakin ?\')"><i class="fa fa-fw fa-trash"></i></a>
        $this->datatables->add_column('action','
            <a href="'.base_url('data_pemasangan_alat/read/$1').'" class="btn btn-sm btn-flat btn-default"><i class="fa fa-fw fa-eye"></i></a>
            <a href="'.base_url('data_pemasangan_alat/update/$1').'" class="btn btn-sm btn-flat btn-default"><i class="fa fa-fw fa-pencil"></i></a>
            <a href="'.base_url('data_pemasangan_alat/delete/$1').'" class="btn btn-sm btn-flat btn-default" onclick="javasciprt: return confirm(\'Apakah anda yakin ?\')"><i class="fa fa-fw fa-trash"></i></a>
            <button class="btn btn-sm btn-flat btn-default" id="$1" data-toggle="modal" data-target="#modal-default" onClick="hapus(this.id)"><i class="fa fa-fw fa-arrow-circle-down"></i></button>', 'id_pemasangan_alat');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_aktif()
    {
        $this->db->where('status_pemasangan','aktif');
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->join('mms7.detjual', 'penyusutan.data_pemasangan_alat.nota = mms7.detjual.nota');
        $this->db->where('id_alat = kode');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pemasangan_alat', $q);
	$this->db->or_like('tanggal_pemasangan', $q);
	$this->db->or_like('type_user', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('id_alat', $q);
	$this->db->or_like('jumlah_alat', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('umur_alat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pemasangan_alat', $q);
	$this->db->or_like('tanggal_pemasangan', $q);
	$this->db->or_like('type_user', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('id_alat', $q);
	$this->db->or_like('jumlah_alat', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('umur_alat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_pemasangan_alat_model.php */
/* Location: ./application/models/Data_pemasangan_alat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-20 03:56:45 */
/* http://harviacode.com */