<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jual_model extends CI_Model
{

    public $table = 'jual';
    public $id = 'nota';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db=$this->load->database('mms7', true);
    }

    // datatables
    function json() {
        $this->datatables->select('nota,tgl,cust,seles,ppn,diskon,pot,biaya,total,bayar,sisa,tempo,opr,retur');
        $this->datatables->from('jual');
        //add this line for join
        //$this->datatables->join('table2', 'jual.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jual/read/$1'),'Read')." | ".anchor(site_url('jual/update/$1'),'Update')." | ".anchor(site_url('jual/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'nota');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('nota', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('cust', $q);
	$this->db->or_like('seles', $q);
	$this->db->or_like('ppn', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('pot', $q);
	$this->db->or_like('biaya', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('sisa', $q);
	$this->db->or_like('tempo', $q);
	$this->db->or_like('opr', $q);
	$this->db->or_like('retur', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nota', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('cust', $q);
	$this->db->or_like('seles', $q);
	$this->db->or_like('ppn', $q);
	$this->db->or_like('diskon', $q);
	$this->db->or_like('pot', $q);
	$this->db->or_like('biaya', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('sisa', $q);
	$this->db->or_like('tempo', $q);
	$this->db->or_like('opr', $q);
	$this->db->or_like('retur', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function search($key=null){
        $this->db->like('nota', $key , 'both');
        $this->db->order_by('nota', 'ASC');
        $this->db->limit(10);
        return $this->db->get($this->table)->result();
    }
}

/* End of file Jual_model.php */
/* Location: ./application/models/Jual_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-12 15:08:10 */
/* http://harviacode.com */